### PR TITLE
Allow Compilation of SteamWebAPI

### PR DESCRIPTION
**Pull request by jpreese**
This PR fixes issue #13 and puts the project into its own solution so the NuGet package manager can be leveraged for the Newtonsoft JSON (JSON.NET) dependency.

### CODE REVIEW

**Comment by Overv** [comment]
The effort is much appreciated. I'm afraid I simply don't have time to manage this project right now.

**Comment by jpreese** [comment]
I wouldn't mind being a contributor to this project if you're light on
time.  There were a few other changes that I was going to make after I got
the build up and running.

**Comment by Overv** [comment]
I think that's a good idea. I've added you as a collaborator.

**Comment by jpreese** [comment]
Thanks! I've gone ahead and made some labels and labeled the current open
issues.  I'll open some more issues that I've wanted to knock out as well.

**Pull request merged**
